# Generated by Django 4.2.11 on 2024-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_subscription_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.CharField(
                choices=[("FREE", "FREE"), ("PREMIUM", "PREMIUM")],
                default="FREE",
                max_length=20,
                verbose_name="Subscription choice",
            ),
        ),
    ]
