# Generated by Django 4.2.11 on 2024-05-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Column Name"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "DEFAULT"),
                            ("BLUE", "BLUE"),
                            ("RED", "RED"),
                            ("YELLOW", "YELLOW"),
                            ("GREEN", "GREEN"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                        verbose_name="Column Color",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.board",
                    ),
                ),
            ],
        ),
    ]
