# Generated by Django 4.2.11 on 2024-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "board",
            "0003_card_alter_column_board_board_unique_name_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
